# Machine Learning: Clustering

In [67]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import utils
import pandas as pd
import pandas
from itertools import cycle, islice
import matplotlib.pyplot as plt
from pandas.tools.plotting import parallel_coordinates
import numpy as np

%matplotlib inline

In [6]:
data=pd.read_csv('C:\\Users\\Gaya\\Desktop\\PYTHON\\Data_Science_Microsoft\\Week-7-MachineLearning\\Week-7-MachineLearning\\weather\\minute_weather.csv')

In [7]:
data.columns

Index(['rowID', 'hpwren_timestamp', 'air_pressure', 'air_temp',
       'avg_wind_direction', 'avg_wind_speed', 'max_wind_direction',
       'max_wind_speed', 'min_wind_direction', 'min_wind_speed',
       'rain_accumulation', 'rain_duration', 'relative_humidity'],
      dtype='object')

In [9]:
data.head()

,rowID,hpwren_timestamp,air_pressure,air_temp,avg_wind_direction,avg_wind_speed,max_wind_direction,max_wind_speed,min_wind_direction,min_wind_speed,rain_accumulation,rain_duration,relative_humidity
0,0,2011-09-10 00:00:49,912.3,64.76,97.0,1.2,106.0,1.6,85.0,1.0,NaN,NaN,60.5
1,1,2011-09-10 00:01:49,912.3,63.86,161.0,0.8,215.0,1.5,43.0,0.2,0.0,0.0,39.9
2,2,2011-09-10 00:02:49,912.3,64.22,77.0,0.7,143.0,1.2,324.0,0.3,0.0,0.0,43.0
3,3,2011-09-10 00:03:49,912.3,64.40,89.0,1.2,112.0,1.6,12.0,0.7,0.0,0.0,49.5
4,4,2011-09-10 00:04:49,912.3,64.40,185.0,0.4,260.0,1.0,100.0,0.1,0.0,0.0,58.8

In [8]:
data[data.isnull().any(axis=1)]

,rowID,hpwren_timestamp,air_pressure,air_temp,avg_wind_direction,avg_wind_speed,max_wind_direction,max_wind_speed,min_wind_direction,min_wind_speed,rain_accumulation,rain_duration,relative_humidity
0,0,2011-09-10 00:00:49,912.3,64.76,97.0,1.2,106.0,1.6,85.0,1.0,NaN,NaN,60.5
34790,34790,2011-10-04 10:25:48,915.7,51.08,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.0
35929,35929,2011-10-05 05:24:48,915.2,49.64,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,92.0
36320,36320,2011-10-05 11:55:49,914.7,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.9
36321,36321,2011-10-05 11:56:49,914.7,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.9
36322,36322,2011-10-05 11:57:49,914.7,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.9
36323,36323,2011-10-05 11:58:49,914.6,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.9
36324,36324,2011-10-05 11:59:49,914.7,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.9
36325,36325,2011-10-05 12:00:49,914.6,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.9
36326,36326,2011-10-05 12:01:49,914.6,50.00,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,92.0
36327,36327,2011-10-05 12:02:49,914.5,50.18,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,92.0
36328,36328,2011-10-05 12:03:49,914.5,50.18,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,92.0
36329,36329,2011-10-05 12:04:49,914.5,50.18,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,92.0
36330,36330,2011-10-05 12:05:49,914.4,50.18,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,92.0
36331,36331,2011-10-05 12:06:49,914.4,50.18,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.9
64745,64745,2011-10-25 05:40:49,918.6,51.08,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.9
79098,79098,2011-11-04 04:53:50,911.0,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.5
79099,79099,2011-11-04 04:54:50,911.0,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.5
79100,79100,2011-11-04 04:55:50,911.1,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.4
79101,79101,2011-11-04 04:56:50,911.1,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.5
79102,79102,2011-11-04 04:57:50,911.1,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.5
79103,79103,2011-11-04 04:58:50,911.0,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.5
79104,79104,2011-11-04 04:59:50,911.0,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.5
79105,79105,2011-11-04 05:00:50,910.9,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.5
79106,79106,2011-11-04 05:01:50,911.0,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.5
79107,79107,2011-11-04 05:02:50,910.9,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.6
79108,79108,2011-11-04 05:03:50,910.9,48.92,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.6
79250,79250,2011-11-04 07:25:50,910.6,48.02,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.8
79609,79609,2011-11-04 13:24:50,908.6,45.14,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.7
79723,79723,2011-11-04 15:18:50,906.9,46.04,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,91.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1346164,1346164,2014-03-27 08:46:32,917.1,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346165,1346165,2014-03-27 08:47:32,917.1,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346166,1346166,2014-03-27 08:48:32,917.1,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346167,1346167,2014-03-27 08:49:32,917.1,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346168,1346168,2014-03-27 08:50:32,917.1,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346169,1346169,2014-03-27 08:51:32,917.2,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346170,1346170,2014-03-27 08:52:32,917.1,44.60,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346171,1346171,2014-03-27 08:53:32,917.1,44.60,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346172,1346172,2014-03-27 08:54:32,917.1,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346173,1346173,2014-03-27 08:55:32,917.1,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346174,1346174,2014-03-27 08:56:32,917.1,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346175,1346175,2014-03-27 08:57:32,917.0,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346176,1346176,2014-03-27 08:58:32,917.0,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346177,1346177,2014-03-27 08:59:32,917.1,45.14,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346178,1346178,2014-03-27 09:00:32,917.1,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346179,1346179,2014-03-27 09:01:32,917.2,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346180,1346180,2014-03-27 09:02:32,917.1,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346181,1346181,2014-03-27 09:03:32,917.2,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346182,1346182,2014-03-27 09:04:32,917.2,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346183,1346183,2014-03-27 09:05:32,917.2,44.60,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346184,1346184,2014-03-27 09:06:32,917.3,44.60,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346185,1346185,2014-03-27 09:07:32,917.3,44.60,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346186,1346186,2014-03-27 09:08:32,917.3,44.78,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346187,1346187,2014-03-27 09:09:32,917.4,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346188,1346188,2014-03-27 09:10:32,917.3,45.14,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346189,1346189,2014-03-27 09:11:32,917.4,45.14,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346190,1346190,2014-03-27 09:12:32,917.4,45.14,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1346191,1346191,2014-03-27 09:13:32,917.4,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.1
1346192,1346192,2014-03-27 09:14:32,917.5,44.96,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,91.2
1394844,1394844,2014-04-30 06:21:49,916.7,62.06,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,13.8

In [11]:
data.shape

(1587257, 13)

# Making dataset smaller 1/10

In [12]:
data.columns

Index(['rowID', 'hpwren_timestamp', 'air_pressure', 'air_temp',
       'avg_wind_direction', 'avg_wind_speed', 'max_wind_direction',
       'max_wind_speed', 'min_wind_direction', 'min_wind_speed',
       'rain_accumulation', 'rain_duration', 'relative_humidity'],
      dtype='object')

In [34]:
df_sample=data[data['rowID']%10==0]

In [35]:
df_sample.shape

(158726, 13)

In [36]:
data.shape

(1587257, 13)

In [37]:
df_sample.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
rowID,158726.0,793625.000000,458203.937509,0.00,396812.5,793625.00,1190437.50,1587250.00
air_pressure,158726.0,916.830161,3.051717,905.00,914.8,916.70,918.70,929.50
air_temp,158726.0,61.851589,11.833569,31.64,52.7,62.24,70.88,99.50
avg_wind_direction,158680.0,162.156100,95.278201,0.00,62.0,182.00,217.00,359.00
avg_wind_speed,158680.0,2.775215,2.057624,0.00,1.3,2.20,3.80,31.90
max_wind_direction,158680.0,163.462144,92.452139,0.00,68.0,187.00,223.00,359.00
max_wind_speed,158680.0,3.400558,2.418802,0.10,1.6,2.70,4.60,36.00
min_wind_direction,158680.0,166.774017,97.441109,0.00,76.0,180.00,212.00,359.00
min_wind_speed,158680.0,2.134664,1.742113,0.00,0.8,1.60,3.00,31.60
rain_accumulation,158725.0,0.000318,0.011236,0.00,0.0,0.00,0.00,3.12
rain_duration,158725.0,0.409627,8.665523,0.00,0.0,0.00,0.00,2960.00
relative_humidity,158726.0,47.609470,26.214409,0.90,24.7,44.70,68.00,93.00

# Drop columns with mostly na or 0 values.. In this dataset rain_accumulation adn rain_duration are those ones..

In [38]:
del df_sample['rain_accumulation']

In [39]:
del df_sample['rain_duration']

# Drop rows with NA-s

In [40]:
rows_before=df_sample.shape[0]

In [41]:
df_sample=df_sample.dropna()

In [42]:
rows_after=df_sample.shape[0]

In [43]:
rows_before

158726

In [44]:
rows_after

158680

In [45]:
rows_before-rows_after

46

In [46]:
df_sample.columns

Index(['rowID', 'hpwren_timestamp', 'air_pressure', 'air_temp',
       'avg_wind_direction', 'avg_wind_speed', 'max_wind_direction',
       'max_wind_speed', 'min_wind_direction', 'min_wind_speed',
       'relative_humidity'],
      dtype='object')

# Select features for Clustering

In [50]:
features=[ 'air_pressure', 'air_temp',
       'avg_wind_direction', 'avg_wind_speed','max_wind_direction',
       'max_wind_speed','relative_humidity']

In [51]:
select_df=df_sample[features]

In [52]:
select_df.columns

Index(['air_pressure', 'air_temp', 'avg_wind_direction', 'avg_wind_speed',
       'max_wind_direction', 'max_wind_speed', 'relative_humidity'],
      dtype='object')

In [53]:
select_df

,air_pressure,air_temp,avg_wind_direction,avg_wind_speed,max_wind_direction,max_wind_speed,relative_humidity
0,912.3,64.76,97.0,1.2,106.0,1.6,60.5
10,912.3,62.24,144.0,1.2,167.0,1.8,38.5
20,912.2,63.32,100.0,2.0,122.0,2.5,58.3
30,912.2,62.60,91.0,2.0,103.0,2.4,57.9
40,912.2,64.04,81.0,2.6,88.0,2.9,57.4
50,912.1,63.68,102.0,1.2,119.0,1.5,51.4
60,912.0,64.04,83.0,0.7,101.0,0.9,51.4
70,911.9,64.22,82.0,2.0,97.0,2.4,62.2
80,911.9,61.70,67.0,3.3,70.0,3.5,71.5
90,911.9,61.34,67.0,3.6,75.0,4.2,72.5
100,911.8,62.96,95.0,2.3,106.0,2.5,63.9
110,911.8,64.22,83.0,2.1,88.0,2.5,59.1
120,911.8,63.86,68.0,2.1,76.0,2.4,63.5
130,911.6,64.40,156.0,0.5,203.0,0.7,50.4
140,911.5,65.30,85.0,2.2,92.0,2.5,58.0
150,911.4,64.58,154.0,1.3,176.0,2.1,50.2
160,911.4,65.48,154.0,0.9,208.0,1.9,46.2
170,911.5,65.66,95.0,1.1,109.0,1.6,45.2
180,911.4,65.66,155.0,1.1,167.0,1.6,42.8
190,911.4,67.10,157.0,1.2,172.0,1.6,36.8
200,911.4,68.00,53.0,0.3,69.0,0.5,33.4
210,911.3,67.64,167.0,1.5,196.0,2.2,34.4
220,911.4,67.82,4.0,0.6,25.0,0.7,34.2
230,911.4,66.74,172.0,1.3,192.0,1.9,37.8
240,911.4,66.56,39.0,0.2,145.0,0.3,41.6
250,911.4,65.66,56.0,1.9,67.0,2.2,51.8
260,911.5,65.66,74.0,0.8,101.0,1.2,41.1
270,911.4,66.92,147.0,0.9,174.0,1.1,36.0
280,911.3,64.76,73.0,1.0,82.0,1.2,43.3
290,911.3,64.94,164.0,1.3,176.0,1.7,43.0
...,...,...,...,...,...,...,...
1586960,914.7,76.46,247.0,0.6,264.0,0.7,43.4
1586970,914.8,76.28,208.0,0.7,216.0,0.9,43.7
1586980,914.8,76.10,209.0,0.7,216.0,0.9,43.9
1586990,914.9,76.28,339.0,0.5,350.0,0.7,43.4
1587000,914.9,75.92,344.0,0.4,352.0,0.6,43.9
1587010,915.0,75.56,323.0,0.3,348.0,0.5,45.5
1587020,915.1,75.56,324.0,1.1,347.0,1.5,46.0
1587030,915.1,75.74,1.0,1.3,13.0,1.7,45.8
1587040,915.2,75.38,355.0,0.9,1.0,1.1,46.1
1587050,915.3,75.38,359.0,1.4,11.0,1.5,45.8
1587060,915.4,75.38,11.0,1.1,21.0,1.3,45.7
1587070,915.5,75.38,13.0,1.4,24.0,1.6,46.6
1587080,915.6,75.20,18.0,1.0,24.0,1.2,46.5
1587090,915.6,75.20,356.0,1.7,1.0,1.9,47.2
1587100,915.7,75.38,13.0,1.5,24.0,1.7,46.7
1587110,915.7,75.02,19.0,1.2,28.0,1.4,46.7
1587120,915.7,74.84,25.0,1.4,35.0,1.6,46.5
1587130,915.8,74.84,23.0,1.3,30.0,1.5,46.9
1587140,915.8,74.84,32.0,1.4,41.0,1.7,45.5
1587150,915.8,75.20,23.0,1.1,31.0,1.4,45.7
1587160,915.8,75.38,16.0,1.2,28.0,1.5,46.3
1587170,915.7,75.38,347.0,1.2,353.0,1.4,48.1
1587180,915.8,75.74,326.0,1.2,337.0,1.6,48.3
1587190,915.9,75.92,289.0,0.7,309.0,0.9,48.1
1587200,915.9,75.74,335.0,0.9,348.0,1.1,47.8
1587210,915.9,75.56,330.0,1.0,341.0,1.3,47.8
1587220,915.9,75.56,330.0,1.1,341.0,1.4,48.0
1587230,915.9,75.56,344.0,1.4,352.0,1.7,48.0
1587240,915.9,75.20,359.0,1.3,9.0,1.6,46.3
1587250,915.9,74.84,6.0,1.5,20.0,1.9,46.1

# Scale the Features using StandardScaller

In [54]:
X=StandardScaler().fit_transform(select_df)

In [55]:
X

array([[-1.48456281,  0.24544455, -0.68385323, ..., -0.62153592,
        -0.74440309,  0.49233835],
       [-1.48456281,  0.03247142, -0.19055941, ...,  0.03826701,
        -0.66171726, -0.34710804],
       [-1.51733167,  0.12374562, -0.65236639, ..., -0.44847286,
        -0.37231683,  0.40839371],
       ...,
       [-0.30488381,  1.15818654,  1.90856325, ...,  2.0393087 ,
        -0.70306017,  0.01538018],
       [-0.30488381,  1.12776181,  2.06599745, ..., -1.67073075,
        -0.74440309, -0.04948614],
       [-0.30488381,  1.09733708, -1.63895404, ..., -1.55174989,
        -0.62037434, -0.05711747]])

# Use k-means clustering

In [57]:
kmeans=KMeans(n_clusters=12)

In [59]:
model=kmeans.fit(X)

In [60]:

print('model\n',model)

model
 KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=12, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

# Identify center of 12 cluster

In [62]:
centers=model.cluster_centers_

In [63]:
centers

array([[ 0.72986002,  0.43638937,  0.28555571, -0.53484748,  0.47336964,
        -0.54110335, -0.77185939],
       [ 0.2339313 ,  0.31909585,  1.88794143, -0.65198177, -1.55164369,
        -0.57681439, -0.28251551],
       [-0.83984754, -1.19876266,  0.37518149,  0.35687681,  0.47362642,
         0.34479926,  1.36234038],
       [-0.16423264,  0.86390952, -1.31101202, -0.58975125, -1.16671764,
        -0.60507896, -0.64081226],
       [-1.18011263, -0.87555235,  0.44665762,  1.97734342,  0.53863398,
         1.93885741,  0.9137497 ],
       [ 1.36622971, -0.08076671, -1.20733272, -0.05002916, -1.07619482,
        -0.02972204, -0.97772303],
       [ 1.19069497, -0.25534191, -1.15494516,  2.12386288, -1.05346344,
         2.24066994, -1.13459516],
       [-0.21121015,  0.63199625,  0.40854376,  0.73505644,  0.51666908,
         0.67300315, -0.1503089 ],
       [-0.69618458,  0.54317899,  0.17711159, -0.58389288,  0.34645355,
        -0.59725787, -0.11385611],
       [ 0.13086607,  0.84363066,  1.41100869, -0.63839846,  1.67503834,
        -0.58914933, -0.71418457],
       [ 0.25146219, -0.99457552,  0.65963722, -0.54715634,  0.85095405,
        -0.52989086,  1.15842241],
       [ 0.06100833, -0.7887917 , -1.19674129, -0.57094351, -1.04273463,
        -0.58547529,  0.8782675 ]])

# PLots

# Let's define function that takes all cluster-center values and relevant heading for those features to make a dataframe

In [64]:
# Function that creates a DataFrame with a column for Cluster Number

def pd_centers(featuresUsed, centers):
	colNames = list(featuresUsed)
	colNames.append('prediction')

	# Zip with a column called 'prediction' (index)
	Z = [np.append(A, index) for index, A in enumerate(centers)]

	# Convert to pandas data frame for plotting
	P = pd.DataFrame(Z, columns=colNames)
	P['prediction'] = P['prediction'].astype(int)
	return P

  # Function that creates Parallel Plotsion'] = P['prediction'].astype(int)

In [65]:
  # Function that creates Parallel Plots

def parallel_plot(data):
	my_colors = list(islice(cycle(['b', 'r', 'g', 'y', 'k']), None, len(data)))
	plt.figure(figsize=(15,8)).gca().axes.set_ylim([-3,+3])
	parallel_coordinates(data, 'prediction', color = my_colors, marker='o')

In [68]:
P = pd_centers(features, centers)
P

,air_pressure,air_temp,avg_wind_direction,avg_wind_speed,max_wind_direction,max_wind_speed,relative_humidity,prediction
0,0.729860,0.436389,0.285556,-0.534847,0.473370,-0.541103,-0.771859,0
1,0.233931,0.319096,1.887941,-0.651982,-1.551644,-0.576814,-0.282516,1
2,-0.839848,-1.198763,0.375181,0.356877,0.473626,0.344799,1.362340,2
3,-0.164233,0.863910,-1.311012,-0.589751,-1.166718,-0.605079,-0.640812,3
4,-1.180113,-0.875552,0.446658,1.977343,0.538634,1.938857,0.913750,4
5,1.366230,-0.080767,-1.207333,-0.050029,-1.076195,-0.029722,-0.977723,5
6,1.190695,-0.255342,-1.154945,2.123863,-1.053463,2.240670,-1.134595,6
7,-0.211210,0.631996,0.408544,0.735056,0.516669,0.673003,-0.150309,7
8,-0.696185,0.543179,0.177112,-0.583893,0.346454,-0.597258,-0.113856,8
9,0.130866,0.843631,1.411009,-0.638398,1.675038,-0.589149,-0.714185,9
10,0.251462,-0.994576,0.659637,-0.547156,0.850954,-0.529891,1.158422,10
11,0.061008,-0.788792,-1.196741,-0.570944,-1.042735,-0.585475,0.878268,11